import Header from "@/lib/components/Header/Header";
import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "@/lib/components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/sand.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} bg-Peach-92 `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
